### ISSUE TITLE
Not Working with Laravel 11 or Maybe Statamic 5?

### ISSUE THREAD

**Issue by twd3** [acquaint-softtech/geo-location#2]
I can't get this to install using Laravel 11 and Statamic 5?
**I get:**
Problem 1
    - stevebauman/location v6.6.0 requires illuminate/support ^5.0|^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - stevebauman/location[v6.6.1, ..., v6.6.2] require illuminate/support ^5.0|^6.0|^7.0|^8.0|^9.0|^10.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.
    - acquaint-softtech/geo-location[dev-main, dev-1986webdeveloper-patch-1, 0.0.1, ..., v0.0.2] require stevebauman/location ^6.6 -> satisfiable by stevebauman/location[v6.6.0, v6.6.1, v6.6.2].
    - Root composer.json requires acquaint-softtech/geo-location * -> satisfiable by acquaint-softtech/geo-location[dev-main, dev-1986webdeveloper-patch-1, 0.0.1, v0.0.2, 9999999-dev].

Any help appreciated!

**Comment by 1986webdeveloper** [comment]
Hey @twd3 , Thank you for the create issue. Now you can use with laravel 11 and statamic 5.
